import os
import datetime
from model import User, Category, Item, Trip, TripItem, Template, TemplateItem, connect_to_db, db
from server import app

os.system("dropdb tripster")
os.system("createdb tripster")

connect_to_db(app)
db.create_all()


user = User(
    id=1,
    email="test@test.test",
    password_hash="de34ddf5af5bcbda0219a7280880a0b7c6ae7b12885160996fe3effaa67733a3"
)
#password="koko"

category1 = Category(name="Camping Cookware", user_id=1, deleted=False)
category2 = Category(name="Clothes", user_id=1, deleted=False)
category3 = Category(name="Food", user_id=1, deleted=False)
category4 = Category(name="Gear", user_id=1, deleted=False)
category5 = Category(name="Personal care", user_id=1, deleted=False)
category6 = Category(name="Sleep", user_id=1, deleted=False)


item1 = Item(name="Fuel", category_id=1, user_id=1, deleted=False)
item2 = Item(name="Stove", category_id=1, user_id=1, deleted=False)
item3 = Item(name="Cookpot + lid", category_id=1, user_id=1, deleted=False)
item4 = Item(name="Spoon", category_id=1, user_id=1, deleted=False)
item5 = Item(name="Cup", category_id=1, user_id=1, deleted=False)
item6 = Item(name="Small pocket knife", category_id=1, user_id=1, deleted=False)
item7 = Item(name="Water filter", category_id=1, user_id=1, deleted=False)

item8 = Item(name="Buff", category_id=2, user_id=1, deleted=False)
item9 = Item(name="Down jacket", category_id=2, user_id=1, deleted=False)
item10 = Item(name="Shorts", category_id=2, user_id=1, deleted=False)
item11 = Item(name="Sun hoodie", category_id=2, user_id=1, deleted=False)

item12 = Item(name="Freeze dried dinner", category_id=3, user_id=1, deleted=False)

item13 = Item(name="Tent", category_id=4, user_id=1, deleted=False)
item14 = Item(name="Trekking poles", category_id=4, user_id=1, deleted=False)
item15 = Item(name="Tent stakes", category_id=4, user_id=1, deleted=False)
item16 = Item(name="Tarp", category_id=4, user_id=1, deleted=False)

item17 = Item(name="Hand sanitizer", category_id=5, user_id=1, deleted=False)
item18 = Item(name="Sunscreen", category_id=5, user_id=1, deleted=False)
item19 = Item(name="Toothbrush", category_id=5, user_id=1, deleted=False)
item20 = Item(name="Toothpaste", category_id=5, user_id=1, deleted=False)

item21 = Item(name="Sleeping quilt", category_id=6, user_id=1, deleted=False)
item22 = Item(name="Sleeping pad", category_id=6, user_id=1, deleted=False)
item23 = Item(name="Pillow black", category_id=6, user_id=1, deleted=False)
item24 = Item(name="Sleeping bag liner", category_id=6, user_id=1, deleted=False)
item25 = Item(name="Sleeping bag", category_id=6, user_id=1, deleted=False)


# item13 = Item(name="Banana", category_id=1, user_id=1, deleted=False)
# item14 = Item(name="Bread", category_id=1, user_id=1, deleted=False)
# item15 = Item(name="T-shirt", category_id=2, user_id=1, deleted=False)
# item16 = Item(name="Shoes", category_id=2, user_id=1, deleted=False)

trip1 = Trip(name="Yosemite", trip_date=datetime.date(2021, 9, 18), user_id=1, deleted=False)
trip2 = Trip(name="Santa Cruz", trip_date=datetime.date(2021, 12, 31), user_id=1, deleted=False)
# trip_item1 = TripItem(quantity=5, checked=False, item_id=1, trip_id=1)
# trip1.trip_items.append(trip_item1)
# trip_item2 = TripItem(quantity=3, checked=False, item_id=2, trip_id=1)
# trip1.trip_items.append(trip_item2)
# trip_item3 = TripItem(quantity=1, checked=False, item_id=3, trip_id=1)
# trip1.trip_items.append(trip_item3)
# trip_item4 = TripItem(quantity=2, checked=False, item_id=4, trip_id=2)
# trip2.trip_items.append(trip_item4)


template1 = Template(name="Backpacking", user_id=1, deleted=False)

template_item1 = TemplateItem(item_id=1, template_id=1)
template1.template_items.append(template_item1)
template_item2 = TemplateItem(item_id=2, template_id=1)
template1.template_items.append(template_item2)
template_item3 = TemplateItem(item_id=3, template_id=1)
template1.template_items.append(template_item3)
template_item4 = TemplateItem(item_id=4, template_id=1)
template1.template_items.append(template_item4)
template_item5 = TemplateItem(item_id=5, template_id=1)
template1.template_items.append(template_item5)
template_item6 = TemplateItem(item_id=6, template_id=1)
template1.template_items.append(template_item6)
template_item7 = TemplateItem(item_id=7, template_id=1)
template1.template_items.append(template_item7)
template_item8 = TemplateItem(item_id=8, template_id=1)
template1.template_items.append(template_item8)
template_item9 = TemplateItem(item_id=9, template_id=1)
template1.template_items.append(template_item9)
template_item10 = TemplateItem(item_id=10, template_id=1)
template1.template_items.append(template_item10)
template_item11 = TemplateItem(item_id=11, template_id=1)
template1.template_items.append(template_item11)
template_item12 = TemplateItem(item_id=12, template_id=1)
template1.template_items.append(template_item12)
template_item13 = TemplateItem(item_id=13, template_id=1)
template1.template_items.append(template_item13)
template_item14 = TemplateItem(item_id=14, template_id=1)
template1.template_items.append(template_item14)
template_item15 = TemplateItem(item_id=15, template_id=1)
template1.template_items.append(template_item15)
template_item17 = TemplateItem(item_id=17, template_id=1)
template1.template_items.append(template_item17)
template_item18 = TemplateItem(item_id=18, template_id=1)
template1.template_items.append(template_item18)
template_item19 = TemplateItem(item_id=19, template_id=1)
template1.template_items.append(template_item19)
template_item20 = TemplateItem(item_id=20, template_id=1)
template1.template_items.append(template_item20)
template_item21 = TemplateItem(item_id=21, template_id=1)
template1.template_items.append(template_item21)
template_item22 = TemplateItem(item_id=22, template_id=1)
template1.template_items.append(template_item22)
template_item23 = TemplateItem(item_id=23, template_id=1)
template1.template_items.append(template_item23)
template_item24 = TemplateItem(item_id=24, template_id=1)
template1.template_items.append(template_item24)

template2 = Template(name="Camping", user_id=1, deleted=False)

template_item31 = TemplateItem(item_id=2, template_id=2)
template2.template_items.append(template_item31)
template_item32 = TemplateItem(item_id=3, template_id=2)
template2.template_items.append(template_item32)
template_item33 = TemplateItem(item_id=4, template_id=2)
template2.template_items.append(template_item33)
template_item34 = TemplateItem(item_id=5, template_id=2)
template2.template_items.append(template_item34)
template_item35 = TemplateItem(item_id=9, template_id=2)
template2.template_items.append(template_item35)
template_item36 = TemplateItem(item_id=10, template_id=2)
template2.template_items.append(template_item36)
template_item37 = TemplateItem(item_id=11, template_id=2)
template2.template_items.append(template_item37)
template_item38 = TemplateItem(item_id=13, template_id=2)
template2.template_items.append(template_item38)
template_item39 = TemplateItem(item_id=15, template_id=2)
template2.template_items.append(template_item39)
template_item40 = TemplateItem(item_id=16, template_id=2)
template2.template_items.append(template_item40)
template_item41 = TemplateItem(item_id=19, template_id=2)
template2.template_items.append(template_item41)
template_item42 = TemplateItem(item_id=20, template_id=2)
template2.template_items.append(template_item42)
template_item43 = TemplateItem(item_id=24, template_id=2)
template2.template_items.append(template_item43)
template_item44 = TemplateItem(item_id=25, template_id=2)
template2.template_items.append(template_item44)


db.session.add(user)
db.session.add(category1)
db.session.add(category2)
db.session.add(category3)
db.session.add(category4)
db.session.add(category5)
db.session.add(category6)
db.session.add(item1)
db.session.add(item2)
db.session.add(item3)
db.session.add(item4)
db.session.add(item5)
db.session.add(item6)
db.session.add(item7)
db.session.add(item8)
db.session.add(item9)
db.session.add(item10)
db.session.add(item11)
db.session.add(item12)
db.session.add(item13)
db.session.add(item14)
db.session.add(item15)
db.session.add(item16)
db.session.add(item17)
db.session.add(item18)
db.session.add(item19)
db.session.add(item20)
db.session.add(item21)
db.session.add(item22)
db.session.add(item23)
db.session.add(item24)
db.session.add(item25)
db.session.add(trip1)
db.session.add(trip2)
db.session.add(template1)
db.session.add(template2)


db.session.commit()
